# Generated by Django 6.0.7 on 2026-07-23 14:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('video_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='transcribes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DurationField(null=True)),
                ('end', models.DurationField(null=True)),
                ('text', models.TextField()),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadPage.videos')),
            ],
        ),
    ]
