# Generated by Django 6.0.7 on 2026-07-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcribes',
            old_name='videos',
            new_name='v_id',
        ),
    ]
